apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  kustomize:
    clouddriver:
      deployment:
        patchesStrategicMerge:
          - |
            spec:
              template:
                spec:
                  initContainers:
                    - name: mysql-extra-lib-init
                      image: armory/mysql-extra-lib:clouddriver-2.26.6
                      volumeMounts:
                        - mountPath: /target/extra-lib
                          name: extra-lib-vol
                  containers:
                    - name: clouddriver
                      volumeMounts:
                        - mountPath: /opt/clouddriver/lib
                          name: extra-lib-vol
                        - mountPath: /opt/clouddriver/bin
                          name: extra-lib-vol
                  volumes:
                    - name: extra-lib-vol
                      emptyDir: {}
    orca:
      deployment:
        patchesStrategicMerge:
          - |
            spec:
              template:
                spec:
                  initContainers:
                    - name: mysql-extra-lib-init
                      image: armory/mysql-extra-lib:orca-2.26.12
                      volumeMounts:
                        - mountPath: /target/extra-lib
                          name: extra-lib-vol
                  containers:
                    - name: orca
                      volumeMounts:
                        - mountPath: /opt/orca/lib
                          name: extra-lib-vol
                        - mountPath: /opt/orca/bin
                          name: extra-lib-vol
                  volumes:
                    - name: extra-lib-vol
                      emptyDir: {}
