apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  kustomize: null
  spinnakerConfig:
    config:
      persistentStorage:
        persistentStoreType: s3
        s3:
          accessKeyId: minio
          bucket: spinnaker
          endpoint: http://minio:9000
          pathStyleAccess: true
          region: us-west-2
          rootFolder: front50
          secretAccessKey: encrypted:k8s!n:spin-secrets!k:minioAccessKey
      providers:
        kubernetes:
          accounts:
          - cacheThreads: 1
            checkPermissionsOnStartup: true
            liveManifestCalls: false
            name: spinnaker
            onlySpinnakerManaged: false
            providerVersion: V2
            serviceAccount: true
          enabled: true
          primaryAccount: spinnaker
      version: 2.26.0
    profiles:
      orca:
        sql:
          cache:
            enabled: true
            readBatchSize: 500
            writeBatchSize: 300
          connectionPools:
            default:
              default: true
              jdbcUrl: jdbc:mysql://mysql:3306/orca
              password: encrypted:k8s!n:spin-secrets!k:mysqlOrcaPassword
              user: orca_service
            tasks:
              jdbcUrl: jdbc:mysql://mysql:3306/orca
              password: encrypted:k8s!n:spin-secrets!k:mysqlOrcaPassword
              user: orca_service
          enabled: true
          migration:
            jdbcUrl: jdbc:mysql://mysql:3306/orca
            password: encrypted:k8s!n:spin-secrets!k:mysqlOrcaMigratePassword
            user: orca_migrate
          scheduler:
            enabled: false
          taskRepository:
            enabled: true

      clouddriver:
        redis:
          cache:
            enabled: false
          enabled: true
          scheduler:
            enabled: true
          taskRepository:
            enabled: false
        sql:
          cache:
            enabled: true
            readBatchSize: 500
            writeBatchSize: 300
          connectionPools:
            default:
              default: true
              jdbcUrl: jdbc:mysql://mysql:3306/clouddriver
              password: encrypted:k8s!n:spin-secrets!k:mysqlCdPassword
              user: clouddriver_service
            tasks:
              jdbcUrl: jdbc:mysql://mysql:3306/clouddriver
              password: encrypted:k8s!n:spin-secrets!k:mysqlCdPassword
              user: clouddriver_service
          enabled: true
          migration:
            jdbcUrl: jdbc:mysql://mysql:3306/clouddriver
            password: encrypted:k8s!n:spin-secrets!k:mysqlCdMigratePassword
            user: clouddriver_migrate
          scheduler:
            enabled: false
          taskRepository:
            enabled: true
    service-settings:
      clouddriver:
        kubernetes:
          serviceAccountName: spin-sa
  validation:
    providers:
      kubernetes:
        enabled: false
